generateFromHistory:
  description: "Analizza la cronologia acquisti per suggerire prodotti da ricomprare."
  version: "1.1"
  parameters:
    model: "gpt-4o"
    temperature: 0.4
    response_format: 
      type: "json_object"
  prompt: |
    Sei un assistente alla spesa proattivo. Analizza i seguenti dati di cronologia acquisti di un utente e suggerisci i 3 prodotti che è più probabile debba ricomprare a breve. Considera la frequenza media di acquisto e la data dell'ultimo acquisto.

    **Cronologia Acquisti**:
    {{purchaseHistory}}

    Rispondi con un oggetto JSON contenente un array chiamato "suggestions". Ogni oggetto nell'array deve avere le seguenti chiavi: "itemName", "confidence" (da 0.0 a 1.0), "reasoning" (spiegazione in italiano) e "category".

generateFromRequirement:
  description: "Crea una lista della spesa partendo da un'esigenza descritta dall'utente (es. una ricetta)."
  notes: "Temperatura più alta (0.7) per permettere una maggiore 'creatività' nella generazione degli ingredienti."
  version: "1.0"
  parameters:
    model: "gpt-4o"
    temperature: 0.7
    response_format: 
      type: "json_object"
  prompt: |
    L'utente vuole preparare quanto segue: "{{requirement}}".

    Genera una lista di prodotti necessari per soddisfare questa esigenza. Pensa a tutti gli ingredienti o oggetti che potrebbero servire.

    Per ogni prodotto, fornisci un nome, una categoria tra quelle disponibili (Frutta e Verdura, Latticini, Pane e Cereali, Bevande, Uova, Carne e Pesce, Dolci, Surgelati, Casa e Cura, Altri), una quantità suggerita (es. '500g', '1L', '2 confezioni') e una breve motivazione.

    Rispondi esclusivamente con un oggetto JSON contenente un array chiamato "products", seguendo questo formato esatto.