# FILE: server/config/categories.yaml

- Frutta e Verdura
- Pane e Panificati
- Carne
- Pesce
- Salumi e Formaggi
- Latte, Uova e Latticini
- Pasta, Riso e Cereali
- Olio e Condimenti
- Legumi, Farine e Conserve
- Colazione e Dolciumi
- Snack Salati
- Acqua e Bevande
- Vini, Birre e Liquori
- Surgelati e Gelati
- Gastronomia e Piatti Pronti
- Prodotti per l'Infanzia
- Prodotti per Animali
- Igiene e Cura Persona
- Cosmetici
- Pulizia e Cura Casa
- Casalinghi e Bazar
- Tabacchi e Altri Servizi